### ISSUE TITLE
Импорт иконки из набора

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/icons#3]
Сейчас импортировать иконку можно только таким способом? 

```
import { AccountAddMBlackIcon } from '@alfalab/icons/classic/AccountAddMBlackIcon';
```

Хотелось бы, чтобы можно было импортировать так:

```
import { AccountAddMBlackIcon } from '@alfalab/icons/classic';
import { AccountAddMBlackIcon } from '@alfalab/icons-classic';

import AccountAddMBlackIcon from '@alfalab/icons/classic/AccountAddMBlackIcon';
```

Для это можно добавить индексные файлы и экспортировать иконку через `export default`

**Comment by dmitrsavk** [comment]
Сейчас у иконок commonjs экспорты. Если их экспортить из одного файла, то tree-shaking скорее всего не будет работать

**Comment by reme3d2y** [comment]
Это же можно как-то решить?
Насколько я помню, почти у всех импорты +- такие

**Comment by dmitrsavk** [comment]
@reme3d2y 
Как доделаю CI, то гляну еще раз

**Comment by etroynov** [comment]
>Сейчас у иконок commonjs экспорты. Если их экспортить из одного файла, то tree-shaking скорее всего не будет работать

всм не будет работать, откуда такая информация ?

**Comment by dmitrsavk** [comment]
Реализовал такую возможность
